/**
 *
 *  RestfulUsersChatsCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulUsersChatsCtrl.h"
#include <string>



void RestfulUsersChatsCtrl::get(const HttpRequestPtr &req,
                                std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulUsersChatsCtrlBase::get(req, std::move(callback));
}

void RestfulUsersChatsCtrl::create(const HttpRequestPtr &req,
                                   std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulUsersChatsCtrlBase::create(req, std::move(callback));
}
