/**
 *
 *  RestfulNewtableCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulNewtableCtrl.h"
#include <string>



void RestfulNewtableCtrl::get(const HttpRequestPtr &req,
                              std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulNewtableCtrlBase::get(req, std::move(callback));
}

void RestfulNewtableCtrl::create(const HttpRequestPtr &req,
                                 std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulNewtableCtrlBase::create(req, std::move(callback));
}
