/**
 *
 *  RestfulMessagesCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulMessagesCtrl.h"
#include <string>


void RestfulMessagesCtrl::getOne(const HttpRequestPtr &req,
                                 std::function<void(const HttpResponsePtr &)> &&callback,
                                 Messages::PrimaryKeyType &&id)
{
    RestfulMessagesCtrlBase::getOne(req, std::move(callback), std::move(id));
}


void RestfulMessagesCtrl::updateOne(const HttpRequestPtr &req,
                                    std::function<void(const HttpResponsePtr &)> &&callback,
                                    Messages::PrimaryKeyType &&id)
{
    RestfulMessagesCtrlBase::updateOne(req, std::move(callback), std::move(id));
}


void RestfulMessagesCtrl::deleteOne(const HttpRequestPtr &req,
                                    std::function<void(const HttpResponsePtr &)> &&callback,
                                    Messages::PrimaryKeyType &&id)
{
    RestfulMessagesCtrlBase::deleteOne(req, std::move(callback), std::move(id));
}

void RestfulMessagesCtrl::get(const HttpRequestPtr &req,
                              std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulMessagesCtrlBase::get(req, std::move(callback));
}

void RestfulMessagesCtrl::create(const HttpRequestPtr &req,
                                 std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulMessagesCtrlBase::create(req, std::move(callback));
}
