/**
 *
 *  RestfulGroupsCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulGroupsCtrl.h"
#include <string>


void RestfulGroupsCtrl::getOne(const HttpRequestPtr &req,
                               std::function<void(const HttpResponsePtr &)> &&callback,
                               Groups::PrimaryKeyType &&id)
{
    RestfulGroupsCtrlBase::getOne(req, std::move(callback), std::move(id));
}


void RestfulGroupsCtrl::updateOne(const HttpRequestPtr &req,
                                  std::function<void(const HttpResponsePtr &)> &&callback,
                                  Groups::PrimaryKeyType &&id)
{
    RestfulGroupsCtrlBase::updateOne(req, std::move(callback), std::move(id));
}


void RestfulGroupsCtrl::deleteOne(const HttpRequestPtr &req,
                                  std::function<void(const HttpResponsePtr &)> &&callback,
                                  Groups::PrimaryKeyType &&id)
{
    RestfulGroupsCtrlBase::deleteOne(req, std::move(callback), std::move(id));
}

void RestfulGroupsCtrl::get(const HttpRequestPtr &req,
                            std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulGroupsCtrlBase::get(req, std::move(callback));
}

void RestfulGroupsCtrl::create(const HttpRequestPtr &req,
                               std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulGroupsCtrlBase::create(req, std::move(callback));
}
