/**
 *
 *  RestfulConversationMessagesCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulConversationMessagesCtrl.h"
#include <string>



void RestfulConversationMessagesCtrl::get(const HttpRequestPtr &req,
                                          std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulConversationMessagesCtrlBase::get(req, std::move(callback));
}

void RestfulConversationMessagesCtrl::create(const HttpRequestPtr &req,
                                             std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulConversationMessagesCtrlBase::create(req, std::move(callback));
}
