/**
 *
 *  RestfulUsersGroupsCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulUsersGroupsCtrl.h"
#include <string>



void RestfulUsersGroupsCtrl::get(const HttpRequestPtr &req,
                                 std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulUsersGroupsCtrlBase::get(req, std::move(callback));
}

void RestfulUsersGroupsCtrl::create(const HttpRequestPtr &req,
                                    std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulUsersGroupsCtrlBase::create(req, std::move(callback));
}
