/**
 *
 *  RestfulUsersGroupsCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulUsersGroupsCtrlBase.h"

#include "UsersGroups.h"
using namespace drogon;
using namespace drogon_model::chat;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the users_groups table.
 */

class RestfulUsersGroupsCtrl: public drogon::HttpController<RestfulUsersGroupsCtrl>, public RestfulUsersGroupsCtrlBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(RestfulUsersGroupsCtrl::get,"/usersgroups",Get,Options);
    ADD_METHOD_TO(RestfulUsersGroupsCtrl::create,"/usersgroups",Post,Options);
    //ADD_METHOD_TO(RestfulUsersGroupsCtrl::update,"/usersgroups",Put,Options);
    METHOD_LIST_END
     
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
