/**
 *
 *  RestfulChatsCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulChatsCtrlBase.h"

#include "Chats.h"
using namespace drogon;
using namespace drogon_model::chat;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the chats table.
 */

class RestfulChatsCtrl: public drogon::HttpController<RestfulChatsCtrl>, public RestfulChatsCtrlBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(RestfulChatsCtrl::getOne,"/chats/{1}",Get,Options);
    ADD_METHOD_TO(RestfulChatsCtrl::updateOne,"/chats/{1}",Put,Options);
    ADD_METHOD_TO(RestfulChatsCtrl::deleteOne,"/chats/{1}",Delete,Options);
    ADD_METHOD_TO(RestfulChatsCtrl::get,"/chats",Get,Options);
    ADD_METHOD_TO(RestfulChatsCtrl::create,"/chats",Post,Options);
    //ADD_METHOD_TO(RestfulChatsCtrl::update,"/chats",Put,Options);
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                Chats::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Chats::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Chats::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
