/**
 *
 *  RestfulNewtableCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulNewtableCtrlBase.h"

#include "Newtable.h"
using namespace drogon;
using namespace drogon_model::chat;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the newtable table.
 */

class RestfulNewtableCtrl: public drogon::HttpController<RestfulNewtableCtrl>, public RestfulNewtableCtrlBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(RestfulNewtableCtrl::get,"/newtable",Get,Options);
    ADD_METHOD_TO(RestfulNewtableCtrl::create,"/newtable",Post,Options);
    //ADD_METHOD_TO(RestfulNewtableCtrl::update,"/newtable",Put,Options);
    METHOD_LIST_END
     
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
