/**
 *
 *  RestfulConversationsCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulConversationsCtrlBase.h"

#include "Conversations.h"
using namespace drogon;
using namespace drogon_model::chat;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the conversations table.
 */

class RestfulConversationsCtrl: public drogon::HttpController<RestfulConversationsCtrl>, public RestfulConversationsCtrlBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(RestfulConversationsCtrl::getOne,"/conversations/{1}",Get,Options);
    ADD_METHOD_TO(RestfulConversationsCtrl::updateOne,"/conversations/{1}",Put,Options);
    ADD_METHOD_TO(RestfulConversationsCtrl::deleteOne,"/conversations/{1}",Delete,Options);
    ADD_METHOD_TO(RestfulConversationsCtrl::get,"/conversations",Get,Options);
    ADD_METHOD_TO(RestfulConversationsCtrl::create,"/conversations",Post,Options);
    //ADD_METHOD_TO(RestfulConversationsCtrl::update,"/conversations",Put,Options);
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                Conversations::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Conversations::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Conversations::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
