/**
 *
 *  RestfulUsersChatsCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulUsersChatsCtrlBase.h"

#include "UsersChats.h"
using namespace drogon;
using namespace drogon_model::chat;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the users_chats table.
 */

class RestfulUsersChatsCtrl: public drogon::HttpController<RestfulUsersChatsCtrl>, public RestfulUsersChatsCtrlBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(RestfulUsersChatsCtrl::get,"/userschats",Get,Options);
    ADD_METHOD_TO(RestfulUsersChatsCtrl::create,"/userschats",Post,Options);
    //ADD_METHOD_TO(RestfulUsersChatsCtrl::update,"/userschats",Put,Options);
    METHOD_LIST_END
     
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
