/**
 *
 *  RestfulConversationMessagesCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulConversationMessagesCtrlBase.h"

#include "ConversationMessages.h"
using namespace drogon;
using namespace drogon_model::chat;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the conversation_messages table.
 */

class RestfulConversationMessagesCtrl: public drogon::HttpController<RestfulConversationMessagesCtrl>, public RestfulConversationMessagesCtrlBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(RestfulConversationMessagesCtrl::get,"/conversationmessages",Get,Options);
    ADD_METHOD_TO(RestfulConversationMessagesCtrl::create,"/conversationmessages",Post,Options);
    //ADD_METHOD_TO(RestfulConversationMessagesCtrl::update,"/conversationmessages",Put,Options);
    METHOD_LIST_END
     
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
