/**
 *
 *  RestfulParticipantsCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulParticipantsCtrl.h"
#include <string>



void RestfulParticipantsCtrl::get(const HttpRequestPtr &req,
                                  std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulParticipantsCtrlBase::get(req, std::move(callback));
}

void RestfulParticipantsCtrl::create(const HttpRequestPtr &req,
                                     std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulParticipantsCtrlBase::create(req, std::move(callback));
}
