/**
 *
 *  RestfulParticipantsCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulParticipantsCtrlBase.h"

#include "Participants.h"
using namespace drogon;
using namespace drogon_model::chat;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the participants table.
 */

class RestfulParticipantsCtrl: public drogon::HttpController<RestfulParticipantsCtrl>, public RestfulParticipantsCtrlBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(RestfulParticipantsCtrl::get,"/participants",Get,Options);
    ADD_METHOD_TO(RestfulParticipantsCtrl::create,"/participants",Post,Options);
    //ADD_METHOD_TO(RestfulParticipantsCtrl::update,"/participants",Put,Options);
    METHOD_LIST_END
     
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
