/**
 *
 *  RestfulConversationsCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulConversationsCtrl.h"
#include <string>


void RestfulConversationsCtrl::getOne(const HttpRequestPtr &req,
                                      std::function<void(const HttpResponsePtr &)> &&callback,
                                      Conversations::PrimaryKeyType &&id)
{
    RestfulConversationsCtrlBase::getOne(req, std::move(callback), std::move(id));
}


void RestfulConversationsCtrl::updateOne(const HttpRequestPtr &req,
                                         std::function<void(const HttpResponsePtr &)> &&callback,
                                         Conversations::PrimaryKeyType &&id)
{
    RestfulConversationsCtrlBase::updateOne(req, std::move(callback), std::move(id));
}


void RestfulConversationsCtrl::deleteOne(const HttpRequestPtr &req,
                                         std::function<void(const HttpResponsePtr &)> &&callback,
                                         Conversations::PrimaryKeyType &&id)
{
    RestfulConversationsCtrlBase::deleteOne(req, std::move(callback), std::move(id));
}

void RestfulConversationsCtrl::get(const HttpRequestPtr &req,
                                   std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulConversationsCtrlBase::get(req, std::move(callback));
}

void RestfulConversationsCtrl::create(const HttpRequestPtr &req,
                                      std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulConversationsCtrlBase::create(req, std::move(callback));
}
