/**
 *
 *  RestfulChatsCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulChatsCtrl.h"
#include <string>


void RestfulChatsCtrl::getOne(const HttpRequestPtr &req,
                              std::function<void(const HttpResponsePtr &)> &&callback,
                              Chats::PrimaryKeyType &&id)
{
    RestfulChatsCtrlBase::getOne(req, std::move(callback), std::move(id));
}


void RestfulChatsCtrl::updateOne(const HttpRequestPtr &req,
                                 std::function<void(const HttpResponsePtr &)> &&callback,
                                 Chats::PrimaryKeyType &&id)
{
    RestfulChatsCtrlBase::updateOne(req, std::move(callback), std::move(id));
}


void RestfulChatsCtrl::deleteOne(const HttpRequestPtr &req,
                                 std::function<void(const HttpResponsePtr &)> &&callback,
                                 Chats::PrimaryKeyType &&id)
{
    RestfulChatsCtrlBase::deleteOne(req, std::move(callback), std::move(id));
}

void RestfulChatsCtrl::get(const HttpRequestPtr &req,
                           std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulChatsCtrlBase::get(req, std::move(callback));
}

void RestfulChatsCtrl::create(const HttpRequestPtr &req,
                              std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulChatsCtrlBase::create(req, std::move(callback));
}
